services:
  ai-service:
    build:
      context: ..
      dockerfile: container/Dockerfile
    container_name: ai-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ../config.json:/app/config.json
      - ../prompts:/app/prompts

  signal-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-rest-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../signals:/home/.local/share/signal-cli
    environment:
      - MODE=json-rpc
      - AUTO_RECEIVE=true
